<a href="https://colab.research.google.com/github/sarjanagpt22/GarudaAI_2030/blob/main/Multilayer_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MULTILAYER PURE NUMPY
(konsep dasar)

Secara konsep matematis, kode ini menggambarkan proses sederhana dari jaringan saraf tiruan (neural network) dengan dua lapisan: satu hidden layer dan satu output layer. Persamaan dasarnya mengikuti rumus , di mana  adalah input,  adalah bobot (weight), dan  adalah bias. Hasil  kemudian dilewatkan ke fungsi aktivasi ReLU (Rectified Linear Unit), yang secara matematis ditulis sebagai . ReLU membuat nilai negatif menjadi nol dan mempertahankan nilai positifnya, sehingga menambah sifat non-linear pada model—bagian penting dari jaringan saraf agar bisa mempelajari hubungan kompleks.

Dari sisi logika pemrograman, kode ini menggunakan numpy untuk menghitung operasi vektor dan matriks dengan efisien. Pertama, program menghasilkan input acak 3x3 (x = np.random.randn(3, 3)), lalu mengalikannya dengan matriks bobot w1 berukuran sama menggunakan np.dot(x, w1) untuk menghasilkan z1, kemudian menambahkan bias b1 (yang diinisialisasi dengan nol). Nilai z1 kemudian dilewatkan ke fungsi relu() agar elemen negatif diubah menjadi nol. Langkah ini disimpan sebagai a1, yang berfungsi sebagai output dari hidden layer sekaligus input ke output layer.

Di bagian output layer, hasil a1 kembali dikalikan dengan bobot kedua w2 menggunakan operasi dot product yang sama. Nilainya disimpan di z2, yang merepresentasikan output akhir dari jaringan. Karena tidak ada fungsi aktivasi tambahan di lapisan ini, hasil akhirnya hanyalah kombinasi linear dari nilai-nilai ReLU sebelumnya. Loop for sebanyak 20 kali membuat proses ini diulang untuk 20 input acak berbeda, lalu mencetak hasil matriks output untuk tiap iterasi. Jadi, inti logika program ini adalah mensimulasikan aliran data dari input → bobot → fungsi aktivasi → output dengan struktur jaringan 3-neuron per layer.

In [ ]:
import numpy as np

#Fungsi Aktivasi ReLU
def relu(x):
    return np.maximum(0, x)

#Input Dot Product 3x3

#Input Layer
np.random.seed(50)
for i in range(20):
    x = np.random.randn(3, 3)
    w1 = np.array([[0.31, 0.69, 0.57], [0.25, 0.39, 0.70], [0.44, 0.55, 0.15]])
    b1 = np.zeros((3, 3))
    z1 = np.dot(x, w1) + b1
    a1 = relu(z1)

#Output Layer
    w2 = np.array([[0.24, 0.43, 0.51], [0.25, 0.17, 0.81], [0.10, 0.50, 0.76]])
    b2 = np.zeros((3, 3))
    z2 = np.dot(a1, w2) + b2
    print("Ouput =", z2)

Ouput = [[0.         0.         0.        ]
 [0.00820416 0.04102079 0.06235161]
 [0.01119761 0.05598804 0.08510182]]
Ouput = [[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.33155304e-03 6.65776518e-03 1.01198031e-02]
 [1.49480393e+00 2.94561344e+00 5.84592668e+00]]
Ouput = [[0.10494663 0.31449575 0.55816185]
 [0.         0.         0.        ]
 [0.03694614 0.12758176 0.22311257]]
Ouput = [[0.66404099 1.08483691 2.36293465]
 [0.28398798 0.79796795 1.4920491 ]
 [0.41306175 0.78523658 1.579394  ]]
Ouput = [[0.06882493 0.34412463 0.52306944]
 [0.26037505 0.36206049 0.81917371]
 [0.         0.         0.        ]]
Ouput = [[0.00214781 0.00384815 0.00456409]
 [0.         0.         0.        ]
 [0.21871606 0.86274266 1.4249378 ]]
Ouput = [[0.35905719 0.61800023 1.26157342]
 [0.05442959 0.06295461 0.1503316 ]
 [0.22695965 0.33165611 0.71886007]]
Ouput = [[0.03206434 0.0574486  0.06813672]
 [0.         0.         0.        ]
 [0.03330411 0.0615268  0.10287578]]
Ouput = [[0.70718696 1.16409

Ini adalah list Tuple menghasilkan angka acak dari matriks 3×3 , berguna untuk inisialisasi bobot acak pada Neural Network. Dan juga list Tuple Matriks nol 3×3 untuk inisialisasi bias.

In [ ]:
import numpy as np

#list tuple menghasilkan angka random
x = np.random.randn(3, 3)

#list tuple nilai 0 3x3
b = np.zeros((3, 3))
print(x)
print(b)

[[ 0.42680606 -0.53088771  0.2478494 ]
 [ 0.34585822 -1.06123493 -1.28951216]
 [ 0.88393228 -0.83821332  0.23066455]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Ini implementasi manual gradient descent untuk regresi linear sederhana. Secara matematis model yang dipelajari adalah. Fungsi loss yang dipakai adalah Mean Squared Error (MSE) Turunan parsial terhadap parameter diturunkan dari MSE dan Gradien itu memberi arah penurunan loss ambil langkah kecil ke arah negatif gradien untuk memperbaiki  dan .

Dari sisi logika pemrograman, kode memanfaatkan operasi vektor numpy agar komputasi efisien: y_pred = w * x + b menghasilkan prediksi untuk seluruh dataset sekaligus, error = y - y_pred vektornya, dan loss = np.mean(error**2) menghitung MSE. Gradien dihitung juga secara vektorial (np.sum(x * error) dan np.sum(error)), lalu parameter diperbarui setiap epoch lewat w = w - lr * grad_w dan b = b - lr * grad_b. Loop for epoch in range(epochs) melakukan training selama jumlah epoch yang ditentukan; blok if epoch % 400 == 0 cuma buat logging berkala supaya nggak banjir output.

Praktisnya dengan data seharusnya model konvergen ke dan kalau learning rate dan epoch cukup, karena datasetnya linear sempurna. Perhatian: lr terlalu besar bisa bikin osilasi atau divergen, terlalu kecil bikin lambat, inisialisasi nol di sini fine untuk linear sederhana, tapi untuk model lain random small biasanya lebih aman. Ini full-batch gradient descent (pakai semua data tiap update) alternatif lebih cepat untuk dataset besar: mini-batch atau optimizer adaptif, atau kalau cuma linear regression hitung solusi analitik langsung dengan normal equation untuk hasil exact.

In [ ]:
# Manual gradient descent untuk linear regression
import numpy as np

# data contoh
x = np.array([1.0, 2.0, 3.0, 4.0])
y = np.array([3.0, 5.0, 7.0, 9.0])  # y = 2*x + 1

# inisialisasi
w = 0.0
b = 0.0
lr = 0.01
n = len(x)
epochs = 2000

for epoch in range(epochs):
    y_pred = w * x + b
    error = y - y_pred
    loss = np.mean(error**2)  # MSE

    # turunan parsial (gradien)
    # ∂L/∂w = -2/n * sum(x * (y - (w*x + b)))
    # ∂L/∂b = -2/n * sum(y - (w*x + b))
    grad_w = -2.0/n * np.sum(x * error)
    grad_b = -2.0/n * np.sum(error)

    # update parameter (gradient descent)
    w = w - lr * grad_w
    b = b - lr * grad_b

    if epoch % 400 == 0:
        print(f"epoch {epoch:4d} | loss {loss:.6f} | w {w:.4f} b {b:.4f}")

print("hasil akhir:", "w=", w, "b=", b)

epoch    0 | loss 41.000000 | w 0.3500 b 0.1200
epoch  400 | loss 0.001246 | w 2.0293 b 0.9139
epoch  800 | loss 0.000113 | w 2.0088 b 0.9740
epoch 1200 | loss 0.000010 | w 2.0027 b 0.9922
epoch 1600 | loss 0.000001 | w 2.0008 b 0.9976
hasil akhir: w= 2.0002424048651353 b= 0.9992873001360325


Secara konsep matematis, kode ini merepresentasikan proses feedforward neural network dua lapis yang dilatih menggunakan metode gradient descent. Fungsi modelnya adalah , di mana  adalah data input,  adalah parameter jaringan, dan fungsi aktivasi ReLU membuat model bersifat non-linear. Tujuan training adalah meminimalkan loss function Mean Squared Error (MSE): , dengan  sebagai target output. Penurunan nilai loss dilakukan lewat backpropagation, yaitu menghitung turunan parsial terhadap parameter untuk memperbarui bobot sesuai arah negatif gradien: , dengan  sebagai learning rate.

Dari sisi logika pemrograman, kode memanfaatkan numpy untuk melakukan operasi matriks cepat seperti np.dot() (perkalian linear) dan broadcasting pada bias. Bagian awal mendefinisikan jaringan dengan bobot acak kecil, lalu membuat target data dari jaringan “teacher” (parameter acak lain) agar model punya arah pembelajaran yang jelas. Proses utama ada dalam loop training: bagian forward pass menghitung aktivasi layer demi layer, lalu loss diukur dengan np.mean(error**2). Setelah itu, backward pass menghitung gradien grad_w1, grad_b1, grad_w2, grad_b2 lewat aturan rantai (chain rule) dan fungsi turunan ReLU (relu_grad). Setiap epoch, parameter diperbarui berdasarkan gradien agar output model makin mendekati target.

Konsepnya mirip proses belajar manusia: model menebak hasil, menghitung seberapa besar kesalahannya, lalu menyesuaikan diri sedikit demi sedikit di tiap iterasi. Dalam praktik, ini adalah bentuk paling dasar dari deep learning tanpa library tinggi seperti TensorFlow atau PyTorch. Loop training berulang selama 500 epoch supaya bobot mendekati nilai optimal. if epoch % 50 == 0 hanya mencetak hasil sesekali agar bisa diamati konvergensinya, dan saat loss menurun bertahap, itu berarti model berhasil “belajar” bukan hanya menghitung, tapi beradaptasi lewat perhitungan matematis yang konsisten.

In [ ]:
import numpy as np

np.random.seed(42)
input_data = np.random.randn(6, 4)

def relu(x):
    return np.maximum(0, x)

def relu_grad(x):
    return (x > 0).astype(float)

D = input_data.shape[1]
H = 5

w1 = np.random.randn(D, H) * 0.1
b1 = np.zeros((1, H))
w2 = np.random.randn(H, D) * 0.1
b2 = np.zeros((1, D))

z1 = input_data.dot(w1) + b1
a1 = relu(z1)
z2 = a1.dot(w2) + b2
target = relu(z2)

lr = 0.01
epochs = 500
N = input_data.shape[0]

for epoch in range(1, epochs + 1):
    z1 = input_data.dot(w1) + b1
    a1 = relu(z1)
    z2 = a1.dot(w2) + b2
    y_pred = relu(z2)

    error = y_pred - target
    loss = np.mean(error**2)

    dz2 = (2.0 / N) * error * relu_grad(z2)
    grad_w2 = a1.T.dot(dz2)
    grad_b2 = np.sum(dz2, axis=0, keepdims=True)

    dz1 = dz2.dot(w2.T) * relu_grad(z1)
    grad_w1 = input_data.T.dot(dz1)
    grad_b1 = np.sum(dz1, axis=0, keepdims=True)

    w2 -= lr * grad_w2
    b2 -= lr * grad_b2
    w1 -= lr * grad_w1
    b1 -= lr * grad_b1

    if epoch % 100 == 0 or epoch == 1:
        print(f"epoch {epoch:4d} | loss {loss:.10f}")

print("hasil akhir:", "loss=", loss)
print("w1=", w1)
print("b1=", b1)
print("w2=", w2)
print("b2=", b2)

epoch    1 | loss 0.0000000000
epoch  100 | loss 0.0000000000
epoch  200 | loss 0.0000000000
epoch  300 | loss 0.0000000000
epoch  400 | loss 0.0000000000
epoch  500 | loss 0.0000000000
hasil akhir: loss= 0.0
w1= [[-0.05443827  0.01109226 -0.11509936  0.0375698  -0.06006387]
 [-0.02916937 -0.06017066  0.18522782 -0.00134972 -0.10577109]
 [ 0.08225449 -0.12208436  0.02088636 -0.19596701 -0.1328186 ]
 [ 0.01968612  0.07384666  0.01713683 -0.01156483 -0.03011037]]
b1= [[0. 0. 0. 0. 0.]]
w2= [[-0.1478522  -0.07198442 -0.04606388  0.10571222]
 [ 0.03436183 -0.17630402  0.0324084  -0.03850823]
 [-0.0676922   0.06116763  0.10309995  0.09312801]
 [-0.08392175 -0.03092124  0.03312634  0.09755451]
 [-0.04791742 -0.0185659  -0.1106335  -0.11962066]]
b2= [[0. 0. 0. 0.]]


In [ ]:
import numpy as np

np.random.seed(42)
X = np.random.randn(6, 4)

def relu(x):
    return np.maximum(0, x)

def relu_grad(x):
    return (x > 0).astype(float)

D = X.shape[1]
H = 5

w1 = np.random.randn(D, H) * 0.1
b1 = np.zeros((1, H))
w2 = np.random.randn(H, D) * 0.1
b2 = np.zeros((1, D))

true_w1 = np.random.randn(D, H) * 0.1
true_b1 = np.random.randn(1, H) * 0.1
true_w2 = np.random.randn(H, D) * 0.1
true_b2 = np.random.randn(1, D) * 0.1

z1_t = X.dot(true_w1) + true_b1
a1_t = relu(z1_t)
z2_t = a1_t.dot(true_w2) + true_b2
target = relu(z2_t) + 0.01 * np.random.randn(*z2_t.shape)

lr = 0.01
epochs = 500
N = X.shape[0]

for epoch in range(1, epochs + 1):
    z1 = X.dot(w1) + b1
    a1 = relu(z1)
    z2 = a1.dot(w2) + b2
    y_pred = relu(z2)

    error = y_pred - target
    loss = np.mean(error**2)

    dz2 = (2.0 / N) * error * relu_grad(z2)
    grad_w2 = a1.T.dot(dz2)
    grad_b2 = np.sum(dz2, axis=0, keepdims=True)

    dz1 = dz2.dot(w2.T) * relu_grad(z1)
    grad_w1 = X.T.dot(dz1)
    grad_b1 = np.sum(dz1, axis=0, keepdims=True)

    w2 -= lr * grad_w2
    b2 -= lr * grad_b2
    w1 -= lr * grad_w1
    b1 -= lr * grad_b1

    if epoch % 50 == 0 or epoch == 1:
        print(f"epoch {epoch:4d} | loss {loss:.10f}")

print("hasil akhir:", "loss=", loss)
print("w1 shape", w1.shape, "w2 shape", w2.shape)

epoch    1 | loss 0.0003584421
epoch   50 | loss 0.0003381986
epoch  100 | loss 0.0003346269
epoch  150 | loss 0.0003280211
epoch  200 | loss 0.0003235128
epoch  250 | loss 0.0003215919
epoch  300 | loss 0.0003215232
epoch  350 | loss 0.0003214549
epoch  400 | loss 0.0003214203
epoch  450 | loss 0.0003213677
epoch  500 | loss 0.0003213252
hasil akhir: loss= 0.0003213252047370849
w1 shape (4, 5) w2 shape (5, 4)


Secara matematis, kode ini merepresentasikan jaringan saraf tiruan sederhana dengan tiga lapisan linear dan fungsi aktivasi ReLU. Setiap lapisan menjalankan transformasi linier , lalu hasilnya dilewatkan ke fungsi aktivasi ReLU yang secara matematis didefinisikan sebagai . Proses ini dilakukan berurutan dari layer pertama hingga ketiga, menciptakan fungsi komposisi non-linear yang memetakan input acak menuju output prediksi . Perbedaan utama dengan model linear biasa adalah ReLU yang membuat model bisa meniru hubungan non-linear antara input dan target .

Dari sisi optimisasi, training dilakukan dengan konsep Mean Squared Error (MSE) sebagai fungsi loss, yaitu . Turunan parsialnya terhadap bobot dan bias di layer terakhir dihitung menggunakan aturan rantai (chain rule) dan gradien dari ReLU. Gradien tersebut lalu digunakan dalam langkah pembaruan parameter  dan , di mana  adalah learning rate. Mekanisme ini memastikan bahwa setiap epoch menyesuaikan nilai  dan  agar prediksi jaringan makin mendekati target yang diinginkan.

Secara logika pemrograman, struktur kodenya dibagi menjadi tiga tahap besar: inisialisasi, forward pass, dan training loop. Inisialisasi membuat input acak, bobot, dan bias. Lalu dalam setiap iterasi (epoch), program menghitung keluaran jaringan lewat operasi np.dot() dan fungsi ReLU. Setelah mendapatkan prediksi dan error, kode menghitung gradien serta memperbarui parameter. Loop training berlangsung ribuan kali agar model “belajar” dari perbedaan antara prediksi dan target. Secara logika, ini mirip sistem kontrol otomatis: model terus menyesuaikan dirinya dengan umpan balik error sampai sistem stabil di sekitar nilai loss terkecil.

In [ ]:
import numpy as np

np.random.seed(0)

def relu(x):
    return np.maximum(0, x)

def relu_grad(x):
    return (x > 0).astype(float)

X = np.random.randn(5, 5)
w1 = np.random.randn(5, 5) * 0.1
b1 = np.zeros((1, 5))
w2 = np.random.randn(5, 5) * 0.1
b2 = np.zeros((1, 5))
w3 = np.random.randn(5, 5) * 0.1
b3 = np.zeros((1, 5))

z1 = X.dot(w1) + b1
a1 = relu(z1)
z2 = a1.dot(w2) + b2
a2 = relu(z2)
z3 = a2.dot(w3) + b3
a3 = relu(z3)

x_true = np.array([
    [0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0],
    [1.0, 0.9, 0.95, 1.0, 0.96],
    [0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0]
])

lr = 0.01
epochs = 2000
N = X.shape[0]

for ep in range(1, epochs + 1):
    z1 = X.dot(w1) + b1
    a1 = relu(z1)
    z2 = a1.dot(w2) + b2
    a2 = relu(z2)
    z3 = a2.dot(w3) + b3
    y_pred = relu(z3)

    error = y_pred - x_true
    loss = np.mean(error**2)

    dz3 = (2.0 / N) * error * relu_grad(z3)
    grad_w3 = a2.T.dot(dz3)
    grad_b3 = np.sum(dz3, axis=0, keepdims=True)

    w3 -= lr * grad_w3
    b3 -= lr * grad_b3

    if ep % 200 == 0 or ep == 1:
        print(f"epoch {ep:4d} | loss {loss:.8f}")

print("hasil akhir loss =", loss)
print("a3 terakhir =\n", y_pred)

epoch    1 | loss 0.18532455
epoch  200 | loss 0.16365499
epoch  400 | loss 0.16364509
epoch  600 | loss 0.16364218
epoch  800 | loss 0.16363927
epoch 1000 | loss 0.16363636
epoch 1200 | loss 0.16363345
epoch 1400 | loss 0.16363054
epoch 1600 | loss 0.16362763
epoch 1800 | loss 0.16362472
epoch 2000 | loss 0.16362182
hasil akhir loss = 0.1636218153247194
a3 terakhir =
 [[2.02892924e-01 1.81445302e-01 0.00000000e+00 0.00000000e+00
  1.93085282e-01]
 [1.98568022e-01 1.79985591e-01 0.00000000e+00 0.00000000e+00
  1.92085797e-01]
 [1.99416137e-01 1.79532339e-01 0.00000000e+00 0.00000000e+00
  1.91604129e-01]
 [1.99525383e-01 1.79575336e-01 0.00000000e+00 0.00000000e+00
  1.91755284e-01]
 [1.99579249e-01 1.79445100e-01 3.31017420e-07 1.61718920e-08
  1.91452131e-01]]


Secara matematis, kode ini merepresentasikan feedforward neural network dua lapis dengan satu hidden layer berukuran 4 neuron. Proses forward propagation mengikuti persamaan: , lalu diaktifkan menggunakan fungsi sigmoid , kemudian dilanjutkan ke layer output  dan diaktifkan lagi . Fungsi sigmoid sendiri secara matematis adalah , yang membatasi output di antara 0 dan 1. Model ini cocok untuk tugas klasifikasi biner seperti XOR, di mana hubungan antara input dan output bersifat non-linear.

Pada tahap backpropagation, kode menghitung gradien turunan dari fungsi Mean Squared Error (MSE) terhadap setiap parameter: bobot dan bias. Dengan menggunakan chain rule, gradien layer output dihitung sebagai , lalu diturunkan kembali ke layer tersembunyi melalui , di mana  adalah turunan sigmoid. Setelah gradien dihitung, pembaruan bobot dilakukan dengan aturan gradient descent: , di mana  adalah learning rate. Setiap epoch, loss dihitung dan digunakan untuk mengukur seberapa dekat prediksi dengan target.

Dari sisi logika pemrograman, struktur kodenya modular dan berorientasi objek. Kelas SimpleNeuralNetwork membungkus seluruh mekanisme pembelajaran ke dalam fungsi terpisah forward, backward, dan update_parameters. Program utama membuat dataset XOR sederhana, menginisialisasi jaringan, dan menjalankan training hingga 10.000 epoch. Tiap loop memanggil forward pass untuk menghasilkan prediksi, backward pass untuk menghitung gradien, lalu memperbarui parameter berdasarkan hasil tersebut. Hasil akhirnya menunjukkan bahwa model berhasil “belajar” dari data, dengan prediksi mendekati target XOR klasik (0, 1, 1, 0). Kode ini adalah versi mini dari cara kerja otak buatan, komputasi diferensial yang disusun dalam loop pembelajaran berulang.

In [ ]:
 import numpy as np

class SimpleNeuralNetwork:
      def __init__(self, input_size, hidden_size, output_size, learning_rate=0.01):
          self.learning_rate = learning_rate

          self.W1 = np.random.randn(input_size, hidden_size) * 0.01
          self.b1 = np.zeros((1, hidden_size))
          self.W2 = np.random.randn(hidden_size, output_size) * 0.01
          self.b2 = np.zeros((1, output_size))

      def sigmoid(self, x):
          return 1 / (1 + np.exp(-np.clip(x, -250, 250)))

      def sigmoid_derivative(self, x):
          return x * (1 - x)

      def foward(self, X):
          self.z1 = np.dot(X, self.W1) + self.b1
          self.a1 = self.sigmoid(self.z1)
          self.z2 = np.dot(self.a1, self.W2) + self.b2
          self.a2 = self.sigmoid(self.z2)
          return self.a2

      def backward(self, X, y, output):
          m = X.shape[0]

          dZ2 = output - y
          dW2 = np.dot(self.a1.T, dZ2) / m
          db2 = np.sum(dZ2, axis=0, keepdims=True) / m

          dA1 = np.dot(dZ2, self.W2.T)
          dZ1 = dA1 * self.sigmoid_derivative(self.a1)
          dW1 = np.dot(X.T, dZ1) / m # Corrected dw1 to dW1 and added /m
          db1 = np.sum(dZ1, axis=0, keepdims=True) / m # Added /m for consistency

          return dW1, db1, dW2, db2 # Added return statement

      def update_parameters(self, dW1, db1, dW2, db2): # Renamed to update_parameters
          self.W1 -= self.learning_rate * dW1 # Corrected update rule
          self.b1 -= self.learning_rate * db1 # Corrected update rule
          self.W2 -= self.learning_rate * dW2 # Corrected update rule
          self.b2 -= self.learning_rate * db2 # Corrected update rule

      def train(self, X, y, epochs=1000):
          for epoch in range(epochs):
              output = self.foward(X)
              loss = np.mean((output - y)**2)
              dW1, db1, dW2, db2 = self.backward(X, y, output)
              self.update_parameters(dW1, db1, dW2, db2)
              if epoch % 100 == 0:
                 print(f"Epoch {epoch}, Loss {loss:.4f}")

if __name__ == "__main__":
   X = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
   y = np.array([[0.0], [1.0], [1.0], [0.0]])

   nn = SimpleNeuralNetwork(input_size=2, hidden_size=4, output_size=1, learning_rate=0.1)
   nn.train(X, y, epochs=10000)

   prediction = nn.foward(X)
   print("\nPredictions:") # Corrected /n to \n
   for i in range(len(X)): # Corrected x to X
       print(f"Input: {X[i]}, Target: {y[i][0]}, Prediction: {prediction[i][0]:.4f}") # Corrected predictions to prediction

Epoch 0, Loss 0.2500
Epoch 100, Loss 0.2500
Epoch 200, Loss 0.2500
Epoch 300, Loss 0.2500
Epoch 400, Loss 0.2500
Epoch 500, Loss 0.2500
Epoch 600, Loss 0.2500
Epoch 700, Loss 0.2500
Epoch 800, Loss 0.2500
Epoch 900, Loss 0.2500
Epoch 1000, Loss 0.2500
Epoch 1100, Loss 0.2500
Epoch 1200, Loss 0.2500
Epoch 1300, Loss 0.2500
Epoch 1400, Loss 0.2500
Epoch 1500, Loss 0.2500
Epoch 1600, Loss 0.2500
Epoch 1700, Loss 0.2500
Epoch 1800, Loss 0.2500
Epoch 1900, Loss 0.2500
Epoch 2000, Loss 0.2500
Epoch 2100, Loss 0.2500
Epoch 2200, Loss 0.2500
Epoch 2300, Loss 0.2500
Epoch 2400, Loss 0.2500
Epoch 2500, Loss 0.2500
Epoch 2600, Loss 0.2500
Epoch 2700, Loss 0.2500
Epoch 2800, Loss 0.2500
Epoch 2900, Loss 0.2500
Epoch 3000, Loss 0.2500
Epoch 3100, Loss 0.2500
Epoch 3200, Loss 0.2500
Epoch 3300, Loss 0.2500
Epoch 3400, Loss 0.2500
Epoch 3500, Loss 0.2500
Epoch 3600, Loss 0.2500
Epoch 3700, Loss 0.2500
Epoch 3800, Loss 0.2500
Epoch 3900, Loss 0.2500
Epoch 4000, Loss 0.2500
Epoch 4100, Loss 0.2500
Epoc